### ISSUE TITLE
Swagger 2.0 to OpenAPI v3 Migration

### ISSUE THREAD

**Issue by sruffatti** [openrewrite/rewrite-openapi#1]
## What problem are you trying to solve?
We have many applications using Swagger 2.0 annotations and Swagger 2.0 yaml. We are looking to migrate from Swagger 2.0 to OpenAPI v3.

## What precondition(s) should be checked before applying this recipe?
Does the repo have a Swagger yaml definition?
Does the codebase use Swagger annotations?

## Have you considered any alternatives or workarounds?
Swagger provides an API to convert a yaml declaration. Having a hard time finding anything to convert Swagger annotatinos.

## Are you interested in [contributing this recipe to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#adding-new-recipes)?
Yes, though I have to weigh this work with priorities for current assignments.

**Comment by timtebeek** [comment]
Thanks all! Started a new module and moved this issue here. I think we have enough to start a first pull request if anyone wants to be the first to contribute.

**Comment by timtebeek** [comment]
Glad to hear things mostly worked already!

> Did not change "value" attribute when using default attribute like
> ```
>     @ApiOperation("Pushing PNRGOV message per instance/tenant")
> ```

@tobli was kind enough to notice and fix this in 
- https://github.com/openrewrite/rewrite/pull/3887

**Comment by timtebeek** [comment]
Started a first PR to get this going: https://github.com/openrewrite/rewrite-openapi/pull/2
