### ISSUE TITLE
@ApiModel value property is not changed to name, position is not removed from @ApiModelProperty

### ISSUE THREAD

**Issue by OlegZavrazhin** [openrewrite/rewrite-openapi#16]
## What version of OpenRewrite are you using?

I am using

- Gradle plugin v6.24.0
- org.openrewrite.recipe:rewrite-openapi:0.7.0
- org.openrewrite.recipe:rewrite-testing-frameworks:2.19.0
- OpenJDK 64-Bit Server VM Corretto-11.0.22.7.1 (build 11.0.22+7-LTS, mixed mode) (migrating from it to 17)
- Gradle 5.2.1 (because I'm migrating from it to 7.3.3)
- MacOS

## How are you running OpenRewrite?

I am using the Gradle plugin, and my project is a multi module project.
I run it as a Gradle init script.

```groovy
initscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2"
        }
    }
    dependencies {
        classpath("org.openrewrite:plugin:6.24.0")
    }
}

rootProject {
    plugins.apply(org.openrewrite.gradle.RewritePlugin)

    dependencies {
        rewrite("org.openrewrite.recipe:rewrite-openapi:0.7.0")
        rewrite("org.openrewrite.recipe:rewrite-testing-frameworks:2.19.0")
    }

    rewrite {
        //swagger open doc
        activeRecipe("org.openrewrite.openapi.swagger.MigrateApiToTag")
        activeRecipe("org.openrewrite.openapi.swagger.MigrateApiImplicitParamsToParameters")
        activeRecipe("org.openrewrite.openapi.swagger.MigrateApiOperationToOperation")
        activeRecipe("org.openrewrite.openapi.swagger.MigrateApiParamToParameter")
        activeRecipe("org.openrewrite.openapi.swagger.MigrateApiResponsesToApiResponses")
        activeRecipe("org.openrewrite.openapi.swagger.MigrateApiModelPropertyToSchema")
        activeRecipe("org.openrewrite.openapi.swagger.ConvertApiResponseCodesToStrings")
        activeRecipe("org.openrewrite.openapi.swagger.SwaggerToOpenAPI")
    }

    afterEvaluate {
        if (repositories.isEmpty()) {
            repositories {
                mavenCentral()
            }
        }
    }
}
```

## What is the smallest, simplest way to reproduce the problem?

```java
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@JsonTypeName("SampleDTO")
@ApiModel(value = "SampleDTO", description = "DTO to define a Error")
public class SampleDTO {
    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = -5767555253263397432L;

    private List<SampleDTO> errorDTOs;

    /**
     * Time and date the error was thrown
     */
    @ApiModelProperty(value = "Time and date the error was thrown", position = 1)
    @Builder.Default
    private LocalDateTime dateTime = LocalDateTime.now();

    /** The code. */
    @ApiModelProperty(value = "Error code", position = 2)
    private String code;
}
```

## What did you expect to see?

```java
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@JsonTypeName("SampleDTO")
@Schema(name = "SampleDTO", description = "DTO to define a Error")
public class SampleDTO {
    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = -5767555253263397432L;

    private List<SampleDTO> errorDTOs;

    /**
     * Time and date the error was thrown
     */
    @Schema(description = "Time and date the error was thrown")
    @Builder.Default
    private LocalDateTime dateTime = LocalDateTime.now();

    /** The code. */
    @Schema(description = "Error code")
    private String code;
}
```

## What did you see instead?

```java
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@JsonTypeName("SampleDTO")
@Schema(value = "SampleDTO", description = "DTO to define a Error")
public class SampleDTO {
    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = -5767555253263397432L;

    private List<SampleDTO> errorDTOs;

    /**
     * Time and date the error was thrown
     */
    @Schema(description = "Time and date the error was thrown", position = 1)
    @Builder.Default
    private LocalDateTime dateTime = LocalDateTime.now();

    /** The code. */
    @Schema(description = "Error code", position = 2)
    private String code;
}
```

## What is the full stack trace of any errors you encountered?

```
BUILD SUCCESSFUL in 38s
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

I expect `value` changed to `name` in `@ApiModel` and `position` property removed from `@ApiModelProperty`
NP, I may contribute. I just need to understand if it's not implemented.
There is a chance that I misconfigured something or forgot to add to my script.

Thank you in advance.

**Comment by OlegZavrazhin** [comment]
Additional question: does the script supposed to update `@Configuration`?

**Comment by timtebeek** [comment]
Hi @OlegZavrazhin ; thanks for the detailed report! From a quick look these steps are merely missing. A contribution would be much appreciated!

We already rename the annotation here:
https://github.com/openrewrite/rewrite-openapi/blob/e8cc01cf853c816a786c5d0b35ee3ce51e12cef9/src/main/resources/META-INF/rewrite/swagger-2.yml#L52-L54

Elsewhere we rename annotation properties here:
https://github.com/openrewrite/rewrite-openapi/blob/e8cc01cf853c816a786c5d0b35ee3ce51e12cef9/src/main/resources/META-INF/rewrite/swagger-2.yml#L122-L125

That same recipe file contains quite a few examples of what's likely needed. Even a draft pull request would be appreciated!

**Comment by OlegZavrazhin** [comment]
@timtebeek hello.
I created [PR](https://github.com/openrewrite/rewrite-openapi/pull/17/files). Let me know if I need to apply any changes.

**Comment by timtebeek** [comment]
Thanks again @OlegZavrazhin !

**Comment by santokhsingheng2** [comment]
Hi @timtebeek 
This particular org.openrewrite.openapi.swagger.SwaggerToOpenAPI recipe is leaving "response" attribute unchanged. Seems like a bug?

```
Before 
-            @ApiResponse(code = 200, message = "Success", response = SomeClass.class),
-            @ApiResponse(code = 400, message = "Validation or business error", response = ErrorResponse.class),

After
+            @ApiResponse(responseCode = "200", description = "Success", response = SomeClass.class),
+            @ApiResponse(responseCode = "400", description = "Validation or business error", response = ErrorResponse.class),

```

**Comment by steve-aom-elliott** [comment]
- Related finding from debugging the test above (summarized with an example with fewer dependencies): https://github.com/openrewrite/rewrite/issues/5712
