### ISSUE TITLE
Annotation `@Parameter` does not have property `title`

### ISSUE THREAD

**Issue by b-abel** [openrewrite/rewrite-openapi#19]
## What version of OpenRewrite are you using?

I am using
- Maven plugin v5.43.3

## How are you running OpenRewrite?

I am using the Maven command line, and my project is a single module project.
```bash
 mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-openapi:RELEASE -Drewrite.activeRecipes=org.openrewrite.openapi.swagger.SwaggerToOpenAPI -Drewrite.exportDatatables=true
```

## What is the smallest, simplest way to reproduce the problem?

Have a project with Spring Boot 3.3 and dependency `springdoc-openapi-starter-webmvc-ui` in version 2.6.0 and a controller method annotated with ` @Parameter(description = "")`. The recipe will replace `description` by `title`. This does not compile because the interface `io.swagger.v3.oas.annotations.Parameter` does not have a property `title` in the library `swagger-annotations-jakarta` (version 2.2.22). 

## What did you expect to see?

I expect that it does not change the existing code and leaves it like this: 

```java
public ResponseEntity<MyDto> sayHello(
            @Parameter(description = "The name of the greeter", required = true, example = "John Doe") @PathVariable String name
    ) { }
```

## What did you see instead?
```java
public ResponseEntity<MyDto> sayHello(
            @Parameter(title = "The name of the greeter", required = true, example = "John Doe") @PathVariable String name
    ) { }
```

Can you give me any hints in which version of OpenApi/Springdoc it is supposed to work?

**Comment by timtebeek** [comment]
hi @b-abel ; I indeed do not see such an attribute on the latest version of the Parameter annotation on:
https://javadoc.io/doc/io.swagger.core.v3/swagger-annotations/latest/io/swagger/v3/oas/annotations/Parameter.html

That change was introduced by @amanda-matteucci in 
- https://github.com/openrewrite/rewrite-openapi/pull/15

Perhaps it should have been `Schema` that should have been changed there? Based on this comment:
- https://github.com/openrewrite/rewrite-openapi/pull/15#issuecomment-2374507320

I'd welcome a PR that makes that quick change, provided you both agree on the right path forward. :)

**Comment by santoshdahal12** [comment]
We might also need to update rewrite-spring to have this version ??

**Comment by timtebeek** [comment]
> We might also need to update rewrite-spring to have this version ??

Hi @santoshdahal12 ; rewrite-spring depends on rewrite-openapi, so this change should also be applied there already.
